### ISSUE TITLE
Switch with info cell overlapping with cell text label.

### ISSUE THREAD

**Issue by Miguelaka95** [LacertosusRepo/Preference-Cell-Examples#2]
The default behavior of a long cell text label will truncate at the end of the sentence before it reach the toggle switch. However, the text label doesn't truncate before it reach the info button. The text label and info button overlaps each other. 

This was brought to my attention by a user using my tweak on a iPhone SE (1st generation) - see screenshot.

![image](https://user-images.githubusercontent.com/65593701/155862215-6b548a3f-e5fe-4b2a-9e6b-46773eedc702.jpeg)

**Comment by LacertosusRepo** [comment]
I've run into this issue before, even attempted to force smaller font or two lines. Unfortunately I was unable to figure out a clean solution. Instead I just opted for a alternative look of using a subtitled cell. I could update the info cell with the alternative look if you'd like.

**Comment by Miguelaka95** [comment]
I deleted the issue when I notice you found an alternative method in libDeusPrefs library.

What I did was download "Preferences Example" and modify it to my liking.

But I solve the text issue by modifying the label text. I'll attach the file if you want to take a look at it.

________________________________
